name: Build and Publish Docker Image

on:
  push:
    tags:
      - 'v*'       # Runs only when you push a tag like v1.0.0
    branches:
      - main       # Optional: run on main branch pushes

jobs:
  build:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Determine Docker tag
        id: vars
        run: |
          if [[ "${GITHUB_REF}" == refs/tags/* ]]; then
            VERSION=${GITHUB_REF#refs/tags/}
          elif [[ "${GITHUB_REF}" == refs/heads/* ]]; then
            VERSION=${GITHUB_REF#refs/heads/}
          else
            VERSION=latest
          fi
          VERSION=${VERSION//\//-} # replace any slashes with dashes
          echo "version=$VERSION" >> $GITHUB_OUTPUT

      - name: Build Docker image
        run: |
          IMAGE_NAME=ghcr.io/${{ github.repository }}:${{ steps.vars.outputs.version }}
          echo "Building image: $IMAGE_NAME"
          docker build -t $IMAGE_NAME .
  
      - name: Push Docker image
        run: |
          IMAGE_NAME=ghcr.io/${{ github.repository }}:${{ steps.vars.outputs.version }}
          docker push $IMAGE_NAME