name: Build and Publish Docker Image

on:
  push:
    tags:
      - 'v*'       # Runs only when you push a tag like v1.0.0
    branches:
      - main       # Optional: run on main branch pushes

jobs:
  build:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract version
        id: vars
        run: |
          VERSION=${GITHUB_REF#refs/tags/}
          if [ "$VERSION" = "" ]; then
            VERSION=latest
          fi
          echo "version=$VERSION" >> $GITHUB_OUTPUT

      - name: Build Docker image
        run: |
          docker build -t ghcr.io/${{ github.repository }}:${{ steps.vars.outputs.version }} .

      - name: Push Docker image
        run: |
          docker push ghcr.io/${{ github.repository }}:${{ steps.vars.outputs.version }}
